import './sass/main.scss';
import './js/dom/pagination'
import './js/dom/show-all-films';
import './js/dom/show-searched-films';
import './js/dom/home-library-page-switch';
import './js/dom/modal-group-info';
import './js/dom/loader';
import './js/dom/up-arrow';
import './js/dom/modal-film-info';
import './js/dom/dark-theme';
import './js/storage/add-to-watched';
import './js/storage/add-to-queue';
import './js/dom/show-watched-films';
import './js/dom/show-queue-films';
import './js/storage/dark-theme-ls';
import './js/dom/modal-error';